Add Stars component & new action to productRedux
odevpl/WDP-2201-01 pull request #16
Opened 2022-01-18 15:18 UTC by mikolajszydlo

Before: no hover effect on stars. Stars feature implemented as part of ProductBox component.
Now: Stars feature moved to new Stars component. Add user rate to state. Add hover effect on stars.

2022-01-20 08:25 UTC, katliw commented on src/components/common/ProductBox/ProductBox.js
> +      r<div className={styles.line}></div>
Nadprogramowe 'r' - to chyba ten błąd o którym wspominałeś :-)

2022-01-20 08:31 UTC, katliw requested changes
Wydaje mi się, że wszystko w porządku. Jedynie to 'r', o którym już pisałeś.

2022-01-21 11:16 UTC, mikolajszydlo commented on src/components/common/ProductBox/ProductBox.js
> +      r<div className={styles.line}></div>
OK, poprawione.

2022-01-21 11:32 UTC, katliw approved these changes

2022-01-22 18:43 UTC, merged