Add WDP220101-33 - Feedback component
odevpl/WDP-2201-01 pull request #17
Opened 2022-01-19 11:33 UTC by MarcNowak

2022-01-20 05:06 UTC, mikolajszydlo requested changes
Świetna robota. Poczepiałem się troszkę styli, żeby komponent był jak najbardziej pixel perfect. Kodu klient tak łatwo nie sprawdzi, ale wielkość czcionki już tak :-)

2022-01-20 05:06 UTC, mikolajszydlo commented on src/components/layout/Feedback/Feedback.module.scss
> +  width: 80px;
Szerokość ikony 60px.

2022-01-20 05:06 UTC, mikolajszydlo commented on src/components/layout/Feedback/Feedback.module.scss
> +  height: 80px;
Wysokość ikony 52px.

2022-01-20 05:06 UTC, mikolajszydlo commented on src/components/layout/Feedback/Feedback.module.scss
> +  border-radius: 10px;
Promień 5px.

2022-01-20 07:39 UTC, MarcNowak commented on src/components/layout/Feedback/Feedback.module.scss
> +      font-size: 10px;
OK

2022-01-20 07:40 UTC, MarcNowak commented on src/components/layout/Feedback/Feedback.js
> +                      alt='smallphoto'
OK

2022-01-20 07:46 UTC, MarcNowak commented on src/components/layout/Feedback/Feedback.module.scss
> +  font-size: 11px;
Czcionka - poprawiona.

Wyrównanie tekstu - zostaje. Na prevce faktycznie wygląda na "left", ale IMO to jest środek po empirycznym sprawdzeniu

2022-01-20 07:49 UTC, MarcNowak commented on src/components/layout/Feedback/Feedback.module.scss
> +  width: 80px;
OK

2022-01-20 07:51 UTC, MarcNowak commented on src/components/layout/Feedback/Feedback.module.scss
> +  height: 80px;
OK

2022-01-20 07:51 UTC, MarcNowak commented on src/components/layout/Feedback/Feedback.module.scss
> +  border-radius: 10px;
OK

2022-01-20 07:53 UTC, MarcNowak commented on src/components/layout/Feedback/Feedback.module.scss
> +    .quoteBox {
OK

2022-01-21 11:28 UTC, mikolajszydlo requested changes

2022-01-21 11:28 UTC, mikolajszydlo commented on src/components/layout/Feedback/Feedback.module.scss
> +    color: #676767;
Sorki, że się czepiam, ale czemu nie do zmiennej ten kolor?

2022-01-23 04:30 UTC, mikolajszydlo requested changes

2022-01-23 04:30 UTC, mikolajszydlo commented on src/components/layout/MenuBar/MenuBar.module.scss
> +          width: 90px;
width: 100%;

2022-01-23 04:30 UTC, mikolajszydlo commented on src/components/layout/MenuBar/MenuBar.module.scss
> +        ul::before {
Dodaj jeszcze proszę: 
left:50%;
top: 50%;
transform: translate(-50%, -50%);

2022-01-23 09:34 UTC, mikolajszydlo approved these changes

2022-01-23 09:38 UTC, odevpl approved these changes

2022-01-23 09:39 UTC, merged