Wdp220101 3
odevpl/WDP-2201-01 pull request #3
Opened 2022-01-12 16:06 UTC by Michalandronik

2022-01-12 23:43 UTC, odevpl requested changes
Hej! Gdzie ten hover i linki?

2022-01-13 09:38 UTC, Michalandronik commented
> Hej! Gdzie ten hover i linki?

problem w tym że na starcie wysłałem commit na branch master, czyli wszystkie zmiany są w projekcie, i "działają" nie widać ich jednak na żadnym commicie z Pull Requesta, nie chcę gdzebać wtym repo i próbować skasowac ten commit na master brancha.

2022-01-13 21:37 UTC, odevpl commented
Ponieważ ticket jest w inprogress, zamykam PR

2022-01-13 21:37 UTC, closed without merging

2022-01-13 22:35 UTC, Michalandronik commented
rozumiem, to nic, rezygnuję z projektu